version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
  weather-service:
    build:
      context: ./services/weather-service
    container_name: weather-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - rabbitmq_nodejs
  weather-dashboard:
    build:
      context: ./services/weather-dashboard
    container_name: weather-dashboard
    depends_on:
      - rabbitmq
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
