version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  user-service:
    build: ./services/user-service
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq

  order-service:
    build: ./services/order-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - rabbitmq

  inventory-service:
    build: ./services/inventory-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - order-service
      - inventory-service
