apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: http  # <-- name for the first port
      port: 15672
      targetPort: 15672
    - name: amqp  # <-- name for the second port
      port: 5672
      targetPort: 5672
