---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        - name: log
          mountPath: /var/log/rabbitmq
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rabbitmq-data-pvc
      - name: log
        persistentVolumeClaim:
          claimName: rabbitmq-log-pvc